version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      # Framework gems
      - dependency-name: chai
        dependency-type: direct
      - dependency-name: mocha
        dependency-type: direct
